### ISSUE TITLE
Seeds for benchmark experiments of UNIFUZZ

### ISSUE THREAD

**Issue by White-Mouse** [UNIFUZZ/unibench#1]
种子对fuzzer的效率影响还是比较大的，为了能更好的复现Unifuzz的实验结果，希望能用和Unifuzz一样的初始种子。

**Comment by zjuchenyuan** [comment]
https://github.com/unifuzz/seeds/tree/master/general_evaluation

**Comment by zjuchenyuan** [comment]
@White-Mouse 
We have released the structured data on the README, and the last column is the seed folder.

https://github.com/unifuzz/unibench/blame/3568494/README.md#L10-L37

**Comment by White-Mouse** [comment]
Thanks a lot！

**Comment by White-Mouse** [comment]
I can't find the seed folders such as tcpdump100,ffmpeg100 and so on.

**Comment by zjuchenyuan** [comment]
> I can't find the seed folders such as tcpdump100,ffmpeg100 and so on.

Sorry, we forget and just released them. You can take a look now.
